### ISSUE TITLE
Letter images need to be shown in "edit" mode

### ISSUE THREAD

**Issue by MonikaBarget** [Maynooth-Center-for-Digital-Humanities/omeka-deploy#4]
When letters in OMEKA are opened to be edited, the letters images need to be shown next to the Dublin Core fields. Otherwise no proofing of metadata is possible.

**Comment by fabianoP** [comment]
This is the default behaviour of Omeka, the live server has  the same issue. We need more view, if it is not present it is a new feature and not a bug.

**Comment by MonikaBarget** [comment]
![image](https://user-images.githubusercontent.com/38257338/39179218-a9867af0-47ab-11e8-8399-39775bfdc1f2.png)

**Comment by MonikaBarget** [comment]
The screenshot shows the "edit item" view in OMEKA. I cannot check metadata if I cannot see the letter images at the same time. Can they be displayed on the right hand side or in some kind of pop-up?

**Comment by fabianoP** [comment]
as option, you can open the image in a separate tag. This is an Omeka behaviour and we cannot change it.
